name: Docker Container

on: push

jobs:
  node-docker:
    runs-on: ubuntu-latest
    container:
      image: node:19-alpine3.16
    steps:
      - name: log versions
        run: |
          node -v
          cat /etc/os-release

          