name: Environment Workflow

# on: push
env:
  WF_ENV: ${{ secrets.WF_ENV }}

jobs:
  log-env:
    runs-on: ubuntu-latest
    env:
      LG_ENV: avaliable inside this JOB 01 only
    steps:
      - name: Logging environment variables
        env:
          SP_ENV: Avaliable only this step
        run: |
          echo "actor: $GITHUB_ACTOR"
          echo "repo: $GITHUB_REPOSITORY"
          echo "workspace: $GITHUB_WORKSPACE"
          echo "token: $GITHUB_TOKEN"
          echo "Sha: $GITHUB_SHA"
          echo "REF: $GITHUB_REF"
          echo "HOME: $HOME"
          echo "Event name: $GITHUB_EVENT_NAME"
          echo "Github owner: ${{ github.repository_owner }}"
          echo "token secret: ${{ secrets.GITHUB_TOKEN }}"
          echo "ENV-> workflow: ${WF_ENV}"
          echo "ENV-> Log: ${LG_ENV}"
          echo "ENV-> step: ${SP_ENV}"
  new-log-env:
    runs-on: ubuntu-latest
    steps:
      - name: Logging environment variables
        run: |
          echo "actor: $GITHUB_ACTOR"
          echo "repo: $GITHUB_REPOSITORY"
          echo "workspace: $GITHUB_WORKSPACE"
          echo "token: $GITHUB_TOKEN"
          echo "Sha: $GITHUB_SHA"
          echo "REF: $GITHUB_REF"
          echo "HOME: $HOME"
          echo "Event name: $GITHUB_EVENT_NAME"
          echo "Github owner: ${{ github.repository_owner }}"
          echo "token secret: ${{ secrets.GITHUB_TOKEN }}"
          echo "ENV-> workflow: ${WF_ENV}"
          echo "ENV-> Log: ${LG_ENV}"
          echo "ENV-> step: ${SP_ENV}"