name: Environment Workflow

on: push
env:
  WF_ENV: avaliable in workflow top-level

jobs:
  log-env:
    runs-on: ubuntu-latest
    env:
      LG_ENV: avaliable inside this JOB 01 only
    steps:
      - name: Logging environment variables
        env:
          SP_ENV: Avaliable only this step
        run: |
          echo "actor: $GITHUB_ACTOR"
          echo "repo: $GITHUB_REPOSITORY"
          echo "workspace: $GITHUB_WORKSPACE"
          echo "token: $GITHUB_TOKEN"
          echo "Github owner: ${{ github.repository_owner }}"
          echo "${{ secrets.GITHUB_TOKEN }}"
          echo "ENV-> workflow: ${ WF_ENV }"
          echo "ENV-> Log: ${ LG_ENV }"
          echo "ENV-> step: ${ SP_ENV }"
  new-log-env:
    runs-on: ubuntu-latest
    env:
      LG_ENV: avaliable inside this JOB 02 only
    steps:
      - name: Logging environment variables
        env:
          SP_ENV: Avaliable only this step
        run: |
          echo "actor: $GITHUB_ACTOR"
          echo "repo: $GITHUB_REPOSITORY"
          echo "workspace: $GITHUB_WORKSPACE"
          echo "token: $GITHUB_TOKEN"
          echo "Github owner: ${{ github.repository_owner }}"
          echo "${{ secrets.GITHUB_TOKEN }}"
          echo "ENV-> workflow: ${ WF_ENV }"
          echo "ENV-> Log: ${ LG_ENV }"
          echo "ENV-> step: ${ SP_ENV }"