name: Create issue on commit

on: [ push ]

jobs:
  create_issue:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      repository-projects: write
      issues: write
    steps:
      - name: Create a GitHub repo and create a new file
        run: |
          pwd
          ls -a
          git init
          git remote add origin "https://rmc3408:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git"
          git config --global user.email "rmc3408@protonmail.com"
          git config --global user.name "rmc3408"
          git config --global init.defaultBranch main
          git fetch
          git checkout main
          git pull
          echo $RANDOM >> number.txt
          ls -a
          git add -A
          git commit -m "random-created"
          git push
      - name: Create issue using REST API
        run: |
          curl --request POST \
          --url https://api.github.com/repos/${{ github.repository }}/issues \
          --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          --header 'content-type: application/json' \
          --data '{
            "title": "Automated issue for commit: ${{ github.sha }}",
            "body": "This issue was automatically created by the GitHub Action workflow **${{ github.workflow }}**. \n\n The commit hash was: _${{ github.sha }}_."
            }' \
          --fail