name: Deploy my lambda function - python

on:
  push:
    branches:
     - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: '3.7'
      - name: install linters
        run: |
          cd function
          pip install flake8
      - name: run lint with flake 8
        run: |
          # Select identifies which errors should cause the job to fail
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # The exit zero flag will show errors as warnings and not fail the run
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
          
  build:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: '3.7'
      - name: Install all libraries
        run: |
          cd function
          python -m pip install --upgrade pip
          pip install -r requirements.txt -t .
      - name: Zip bundle
        run: |
          cd function
          zip -r ../${{ github.sha }}.zip .
      - name: Save artifact
        uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: ${{ github.sha }}.zip
          
          
  upload:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: my-artifact
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: us-east-1
      - name: Upload to S3
        run: aws s3 cp ${{ github.sha}}.zip s3://raph-dev-github-dive-deep/${{ github.sha }}.zip
  
  
  deploy:
    runs-on: ubuntu-latest
    needs: upload
    steps:
      - name: AWS credentials again
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: us-east-1
      - name: Update function to lambda
        run: |
          aws lambda update-function-code --function-name my-github-action-function-01 \
            --s3-bucket raph-dev-github-dive-deep \
            --s3-key ${{ github.sha }}.zip --publish
            
  docs:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Deploy docs
        uses: mhausenblas/mkdocs-deploy-gh-pages@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CONFIG_FILE: mkdocs.yaml
  
  
  
  
  
  
  
  
  
      
