name: First Check after pull request in Develop branch

on:
  pull_request:
    branches: [develop]

jobs:
  building:
    runs-on: ubuntu-latest
    steps:
      - name: Getting file from github via checkout action
        uses: actions/checkout@v3
      - name: selecting node version
        uses: actions/setup-node@v2
        with:
          node-version: "12.x"
      - name: Install dependencies via NPM
        run: npm ci
      - name: Check formating via prettier
        run: npm run format:check
      - name: Check Jest testing
        env:
          CI: true
        run: npm run test

  